# Generated by Django 4.1.13 on 2024-09-17 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vocab.models


class Migration(migrations.Migration):

    replaces = [('vocab', '0001_initial'), ('vocab', '0002_remove_persdict_words_pubdict_history_word_pers_dict'), ('vocab', '0003_alter_word_pers_dict'), ('vocab', '0004_alter_word_pers_dict'), ('vocab', '0005_pubdict_slug'), ('vocab', '0006_alter_pubdict_slug'), ('vocab', '0007_alter_word_eng_word'), ('vocab', '0008_usageexample'), ('vocab', '0009_word_hint_word_synonym_word_transcription'), ('vocab', '0010_word_part_of_speech'), ('vocab', '0011_alter_usageexample_eng_text_and_more'), ('vocab', '0012_profile_interests'), ('vocab', '0013_alter_profile_interests'), ('vocab', '0014_remove_word_sample1_eng_remove_word_sample1_rus'), ('vocab', '0015_profile_coins'), ('vocab', '0016_alter_profile_coins'), ('vocab', '0017_wordpict'), ('vocab', '0018_pubdict_picture'), ('vocab', '0019_pubdict_description_pubdict_level'), ('vocab', '0020_alter_pubdict_slug'), ('vocab', '0021_alter_pubdict_slug'), ('vocab', '0022_profile_hint_type'), ('vocab', '0023_alter_pubdict_dict_name_alter_pubdict_slug'), ('vocab', '0024_profile_selected_dict_names'), ('vocab', '0025_profile_treasure'), ('vocab', '0026_reward'), ('vocab', '0027_profile_reward_id'), ('vocab', '0028_word_uk_pronunciation_audio_and_more'), ('vocab', '0029_remove_word_transcription_and_more'), ('vocab', '0030_alter_profile_selected_dict_names'), ('vocab', '0031_alter_profile_selected_dict_names'), ('vocab', '0032_alter_profile_selected_dict_names'), ('vocab', '0033_alter_profile_selected_dict_names'), ('vocab', '0034_alter_profile_selected_dict_names'), ('vocab', '0035_uniqueengword_and_more'), ('vocab', '0036_remove_wordpronunciation_unique_word_accent_and_more'), ('vocab', '0037_word_unique_word'), ('vocab', '0038_rename_unique_word_word_u_eng_word')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_word', models.CharField(max_length=50, verbose_name='English')),
                ('rus_word', models.CharField(max_length=50, verbose_name='Russian')),
                ('sample1_eng', models.TextField(blank=True, verbose_name='English example')),
                ('sample1_rus', models.TextField(blank=True, verbose_name='Русский перевод')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_date', models.DateField()),
                ('ch_result', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.word')),
            ],
        ),
        migrations.CreateModel(
            name='PersDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='pers_dict',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.persdict'),
        ),
        migrations.CreateModel(
            name='PubDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('published', models.BooleanField(default=False)),
                ('words', models.ManyToManyField(related_name='words', to='vocab.word')),
                ('history', models.ManyToManyField(blank=True, related_name='pub_dicts', to='vocab.history')),
                ('slug', vocab.models.RussianAutoSlugField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dictionary_images/')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('level', models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All level', 'All level')], max_length=20, verbose_name='Level')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='eng_word',
            field=models.CharField(db_index=True, max_length=50, verbose_name='English'),
        ),
        migrations.AddField(
            model_name='word',
            name='hint',
            field=models.TextField(blank=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='word',
            name='synonym',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Синоним'),
        ),
        migrations.AddField(
            model_name='word',
            name='transcription',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(blank=True, choices=[('Noun', 'Noun'), ('Verb', 'Verb'), ('Adjective', 'Adjective'), ('Adverb', 'Adverb'), ('Preposition', 'Preposition'), ('Conjunction', 'Conjunction'), ('Interjection', 'Interjection'), ('Article', 'Article')], max_length=50, verbose_name='Часть речи'),
        ),
        migrations.CreateModel(
            name='UsageExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_text', models.TextField(blank=True, verbose_name='English example')),
                ('rus_text', models.TextField(blank=True, verbose_name='Русский пример')),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_examples', to='vocab.word')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='rus_word',
            field=models.CharField(blank=True, max_length=50, verbose_name='Russian'),
        ),
        migrations.RemoveField(
            model_name='word',
            name='sample1_eng',
        ),
        migrations.RemoveField(
            model_name='word',
            name='sample1_rus',
        ),
        migrations.CreateModel(
            name='WordPict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='word_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.word')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=255)),
                ('earned_coins', models.IntegerField(default=0, verbose_name='Количество монет')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('public_dicts', models.ManyToManyField(blank=True, related_name='pub_dicts', to='vocab.pubdict')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('interests', models.TextField(blank=True, verbose_name='interests')),
                ('coins', models.IntegerField(blank=True, default=0, null=True)),
                ('hint_type', models.CharField(blank=True, choices=[('frst_30', 'Первые 30 % букв'), ('rnd_30', '30 % букв в произвольном порядке'), ('all_cap', 'Слово целиком. Большие буквы.')], max_length=50, verbose_name='hint_type')),
                ('selected_dict_names', models.JSONField(default=list)),
                ('treasure', models.IntegerField(blank=True, default=0, null=True)),
                ('reward_id', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='uk_pronunciation_audio',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations/uk/'),
        ),
        migrations.AddField(
            model_name='word',
            name='us_pronunciation_audio',
            field=models.FileField(blank=True, null=True, upload_to='pronunciations/us/'),
        ),
        migrations.CreateModel(
            name='WordPronunciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accent', models.CharField(choices=[('US', 'American'), ('UK', 'British')], max_length=2)),
                ('audio_file', models.FileField(upload_to='word_pronunciations/')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='vocab.word')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wordpronunciation',
            constraint=models.UniqueConstraint(fields=('word', 'accent'), name='unique_word_accent'),
        ),
        migrations.RemoveField(
            model_name='word',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='word',
            name='uk_pronunciation_audio',
        ),
        migrations.RemoveField(
            model_name='word',
            name='us_pronunciation_audio',
        ),
        migrations.AddField(
            model_name='wordpronunciation',
            name='transcription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_dict_names',
            field=models.JSONField(default=['personal']),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_dict_names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_dict_names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_dict_names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_dict_names',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='selected_dict_names',
            field=models.JSONField(default=vocab.models.default_selected_dict_names),
        ),
        migrations.CreateModel(
            name='UniqueEngWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_eng_word', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='English')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='wordpronunciation',
            name='unique_word_accent',
        ),
        migrations.RemoveField(
            model_name='wordpronunciation',
            name='word',
        ),
        migrations.AddField(
            model_name='wordpronunciation',
            name='unique_word',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='pronunciations', to='vocab.uniqueengword'),
        ),
        migrations.AddConstraint(
            model_name='wordpronunciation',
            constraint=models.UniqueConstraint(fields=('unique_word', 'accent'), name='unique_word_accent'),
        ),
        migrations.AddField(
            model_name='word',
            name='u_eng_word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='vocab.uniqueengword'),
        ),
    ]
